### ISSUE TITLE
Cannot find "/dist/bundle.js" in gauge-chart@1.0.0-beta.0

### ISSUE THREAD

**Issue by ellgo** [greetclock/gauge-chart#27]
i cannot load my gauge chart today and i have the error of not finding / dist/bundle.js

**Comment by greetclock** [comment]
Yeah, sorry about that, I published the beta version to the latest channel by mistake.
i recommend you to use 0.5.3 for now. I plan to release final 1.0.0 within next 1-2 weeks.

**Comment by greetclock** [comment]
@ellgo I published `1.0.0` and it should work now. I will close this issue but feel free to reopen it or open another one if you still face problems
